In [5]:
import pandas as pd
import matplotlib.pyplot as plt

# Load data
jabs = pd.read_csv('../data/jabs.csv',encoding = 'utf-16')
hooks = pd.read_csv('../data/hooks.csv', encoding = 'utf-16')
uppercuts = pd.read_csv('../data/uppercuts_left.csv', encoding = 'utf-16')

# Vi arbejder med jabs som eksempel — gentag for de andre
df = jabs
df.head()

   timestamp  accX  accY  accZ  totalAcc  marker
0      15569  -785  -457  -308       959       0
1      15579  -789  -464  -312       967       0
2      15589  -789  -468  -300       965       0
3      15599  -785  -460  -304       960       0
4      15609  -781  -460  -304       956       0

In [6]:
df.describe()

,timestamp,accX,accY,accZ,totalAcc,marker
count,10066.000000,10066.000000,10066.000000,10066.000000,10066.000000,10066.000000
mean,65894.000000,-339.319491,103.305981,-487.835585,1930.177926,0.444765
std,29059.482388,1863.381877,1106.504455,803.392933,1407.369974,0.496964
min,15569.000000,-5476.000000,-6621.000000,-6011.000000,151.000000,0.000000
25%,40731.500000,-1238.000000,-406.000000,-671.000000,1051.000000,0.000000
50%,65894.000000,-863.000000,125.000000,-378.000000,1395.500000,0.000000
75%,91056.500000,-265.000000,699.000000,-85.000000,2328.750000,1.000000
max,116219.000000,10125.000000,5058.000000,2734.000000,10835.000000,1.000000